# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VKTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Analytics'

  # Pods for VKTest
	
  target 'VKTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
